### PR TITLE
Added new string

### PR DESCRIPTION
**Pull request by mm615657**

### CODE REVIEW

**Comment by DingoDjango** [comment]
Looks like HMTB_Tooltip_OpportunisticMode isn't translated all the way, did you miss it maybe?

**Comment by mm615657** [comment]
My bad.Fixed now

**Comment by duduluu** [comment]
You are not worthy to be a translator, you are a thief and robber!
Do not merge this please!

**Comment by mm615657** [comment]
I have no idea how it comes "thief" or "rob", since everything is MIT licensed.Not to mention that I'm just asking for a missing string update.

**Comment by duduluu** [comment]
Of course, a rogue usually open souce lisences as his fig leaf.

**Comment by DingoDjango** [comment]
Care to explain @duduluu ?

**Comment by mm615657** [comment]
I have no idea what are you talking about.It is okay for me to close this pr if @DingoDjango thinks anything here is inappropriate

I don't care it is who are responsible for localization , the thing important is to get new string updated.

**Comment by duduluu** [comment]
@DingoDjango 
In fact, I have a translation team, and many other people work on translating RimWorld mods.
But mostly donot understand how to use git. So they release their translation in some forums.
We told @mm615657, you can help them to create pull request on github.
But @mm615657 said that‘s piracy and donot care about that.

**Comment by mm615657** [comment]
I made this translation  (i.e. a simple line plus 3 short tip) and made this pr all by myself.My obligation is limited to the part I submit,and responsible for any translation quality issue.  I have nothing to do with the translation of others.

Why u have to make this so complicated.I saw an issue, I can fix it , I fixed it then I published it. That is how open source community works.I have no idea what's going wrong.

**Comment by DingoDjango** [comment]
I'm not quite sure what's wrong here @duduluu , nobody is getting money for anything and translation is a community effort. As long as it's accurate and not published without permission by mm I don't see a reason not to accept it...

**Comment by duduluu** [comment]
All right. That's a animosity between he and the WHOLE Chinese translation community.
I'm sorry to disturb you.
I'll commit another translation for you.

**Comment by mm615657** [comment]
I have no idea how it comes to this and why there is someone who claim that it is representing the entire community.I am also a part of community and I'm here just want my language getting up-to-date.I will absolutely willing to take any issue that relevant to localization quality but personal attacks are not this kinds of deal.

**Comment by DingoDjango** [comment]
Alright, I think the bigger picture is (somewhat) clear. I'm going to merge the translation, if the community wants to commit an improved version then I'd be happy to accept it as well.

**Comment by Mirovichka** [comment]
>           Alright, I think the bigger picture is (somewhat) clear. I'm going to merge the translation, if the community wants to commit an improved version then I'd be happy to accept it as well.

Привет Сер 
Hello,sir,Please allow me to explain what happened here.

Some Chinese are professional Chinese translation teams who monopolize the localization of this MOD. It is worth mentioning that this translation team has a “donation” behavior in China. In essence, the Mr. Dulululu is protecting his monopoly interests.

This apparently ignorant  translator translated for this MOD,just bcz he love this mod , but his work were plagiarized by the monopoly organization. Now the organization says: "You are not qualified to publish translation documents here," and then as logical as what them do ,them copyed the translate work , then said that is belong to themselves .

This is a very common behavior in China, but it is not at all fair. I am also a fan of your mod, but I must say that I would rather not use Chinese translation, nor would I like to see this act of tarnishing the goddess of justice.

So the "non-profit" you said is actually very ridiculous. This is the ironclad proof that monopoly capital plunders private translation providers.

**Pull request merged**
